# Generated by Django 4.0.4 on 2022-05-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
